os:
  - linux

language: python

env:
  matrix:
    - python=3.5  CONDA_PY=35  
    - python=3.6  CONDA_PY=36

  global:
    - secure: "u8EtcllIITY5vXHlIWgglJxgnSNcXBKO3w/1EU7jYbMwIEyQnvQUc0e1lCLZvwjfRQIygoW8FdsRaXXf0SQtacODtkvux2cVNS6GiF7hxIcbYHlrZSkc2MC2zuhI8gic0AspJPUaQWG162soWd35sWrW0Cqk76fRkK8d5tavj1IN7/kAGp2jquLlwajwf3dE/FigIQIMkGeePmae304BMEPklMJFv9cqxcSscW7XpNMCU37h90MY1p8G+QgxkFAl79pEKAPTSMcYs/vmQDXeQ1X8ITk8ays0BQBeyByMYolsPWi5EiA+7Fg5WlwBbQVDUcgvCAJhIgXl9Hjf4PsZ+0j6jDi/Vd3tpHluA1daJJB4k06YrCEis7N/lsz5l1L74Nz+38Ic+5nc3jNO2/REOqT6NZB1PLDAWEDqPfYH0TTe716AszJ2TDD/VB0U7GYThGpehQiOLdW0kovmhhQrWWoXTkYxokYzFUb2JvGZcrlwTG8FcARC5rD5z0R7v8ZX4djUD1R+YDU2+2lEmatM8AXw71h1Tuz5MlksJge/gY8D3uw1zMt3KLuYY5VSZekszJR5okvAqAeN9LrroYTfcqet7oygmtHbXhLQXKRW57UGXuL7kCO9Wdd+Whb9o/a9UtikVMMadp9Q5XoStWBRh0EcJM0E5lCjIVmJV55Q3MY="
    - secure:  "T+gFGR3HA/5/jD+IggWxfFVNg8gaaEp0HjtjDXba+dqUBY51wA6n8Yh4C+Lm+i1Lq69frfvxmoS6xuTMUDDdXzRatIhNAvgPYrxG6PTQyV9J+m4q6aqt9Jy2fmJ4WcoSnyanOcD7BSQYslQLtS+zxYJOoel6nPtz35AZCYCeOf7oAXa8ziCBgbIt+j9mMGWX7Mr51ujSwQK9/7Z5pdecy0IsV04TEw7o+2wQgz7+o3bbuKH1/eT08y9j8M2cmpT22jj1zyKouKWjIdRMxsmYwf+84zMkHvRVxQdVBdpjEzrZ/mHf1LBdco6BgM4km6cpP/okw9WtNF6K5iNVa34ZIE4DCH5wVzbFRGqSjOsufgj2ydvMUrP5fwF0PTpMQH+QjkhkQVBA0WxdLk7j0FNJOtmgU0fPCCke72Njd/UeXreuxF6YAF5c0QLEb8sgcHP/7ltIhWuiELBfRpUEDtEWQayia4F+pWpTxGBHOEgYnM+h7bK+e0noLVWowJNgfbQl3Qq9FFY6proHqJlC1G7EV63TIjCIpgTfnUVz1ScnOK78g6Pw/M7KohpCO+1yglMdgoUnQDRV5YRRZKBXE2j+cakKyqGVuwhmaWrYCjl+WH565tz8bUHgKA4VL68rzqinqwHL3xLGAHD7ebKN/XOGUE6pxoRGZG+TykOi5M/lpFM="


before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod 755 miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n ingeotec python=$python
  - source activate ingeotec
  - conda install --yes pip
  - pip install coverage
  - pip install coveralls
  - conda config --append channels ingeotec
  - conda install --yes numpy scipy scikit-learn gensim=2.3.0 nose
  - python setup.py build_ext --inplace
  
script:
  - which python
  - python --version
  - which coverage
  - if [ $python = 3.6 ]; then coverage run setup.py nosetests; fi
  - if [ $python = 3.5 ]; then nosetests --verbose -exe microtc; fi

after_success:
  - if [ $python = 3.6 ]; then coveralls || echo "Coveralls upload failed"; fi
  - if [ $TRAVIS_BRANCH = "master" -a $python = 3.6 ]; then python setup.py sdist; pip install twine; twine upload -u mgraffg -p $TWINE dist/*.tar.gz; fi
  - if [ $TRAVIS_BRANCH = "master" ]; then source deactivate; conda install --yes pip conda-build jinja2 anaconda-client; conda build conda-recipe --quiet; fi
  - python continuous-integration/move-conda-package.py conda-recipe  
  - which binstar
  - python continuous-integration/binstar-push.py

notifications:
    email:
      recipients:
        - mario.graff@infotec.mx
        - eric.tellez@infotec.mx
        - sabino.miranda@infotec.mx
        - dmoctezuma@centrogeo.edu.mx
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
