package:
  name: microtc
  version: "1.3.1"

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - scikit-learn
    - gensim
    - nltk

  run:
    - python

test:
  # Python imports
  imports:
    - microtc

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - microtc-params --help
    - microtc-train --help
    - microtc-predict --help

  requires:
    # Put any additional test requirements here.  For example
    - numpy
    - scipy
    - scikit-learn
    - gensim
    - nltk
about:
  home: https://github.com/ingeotec/microtc
  summary: "A minimalistic approach to text classification (microTC)."
  license: Apache
