package:
  name: microtc
  version: "2.4.0"

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - scikit-learn
  run:
    - python
    - scikit-learn
test:
    requires:
        - nose
        - numpy
        - scipy
        - scikit-learn
        - coverage

    imports:
        - microtc

    commands:
        - nosetests --verbose -exe microtc
        - microtc-predict --help
        - microtc-train --help


about:
  home: https://github.com/ingeotec/microtc
  summary: "A generic minimal text classifier."
  license: APACHE
